# require mkdocs-material 3.x

# Project information
site_name: HttpRunner 中文使用手册
site_description: HttpRunner User Documentation
site_author: 'Leo Lee'

# Repository
repo_name: HttpRunner
repo_url: https://github.com/HttpRunner/HttpRunner
edit_uri: ""

# Copyright
copyright: 'Copyright &copy; 2017 - 2018 debugtalk'

# Configuration
theme:
    name: 'material'
    language: 'zh'
    palette:
        primary: 'indigo'
        accent: 'indigo'
    font:
        text: 'Roboto'
        code: 'Roboto Mono'

# Google Analytics
google_analytics:
    - 'UA-114587036-2'
    - 'auto'

# Extensions
markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: false
  - toc:
      permalink: true

# extra
extra:
    search:
        language: 'en, jp'
    social:
        - type: globe
          link: http://debugtalk.com
        - type: 'github'
          link: 'https://github.com/httprunner'

# index pages
nav:
    - 介绍: index.md
    - 核心概念:
        - 架构图: concept/architecture.md
        - 项目文件类型: concept/filetype.md
    - 安装说明: Installation.md
    - 快速上手: quickstart.md
    - 测试用例:
        - 录制生成用例: testcase/recorder.md
        - 测试用例结构: testcase/structure.md
        - Validate & Prettify: testcase/validate-pretty.md
    - 运行测试: run-test.md
    - 测试报告: report.md
    - 高级特性:
        - hook机制: advanced/request-hook.md
        - 环境变量: advanced/dot-env.md
        - 参数化数据驱动: advanced/parameters.md
        - 测试用例分层: advanced/testcase-layer.md
    - 最佳实践:
        - 信息安全: best-practices/security.md
    - 性能测试: load-test.md
    - 开发扩展: development.md
    - 常见问题: FAQ.md
    - 相关资料: related-docs.md